# Generated by Django 2.2.10 on 2020-08-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('pleasantness', models.FloatField(default=0)),
                ('attention', models.FloatField(default=0)),
                ('sensitivity', models.FloatField(default=0)),
                ('aptitude', models.FloatField(default=0)),
            ],
        ),
    ]
