# Generated by Django 2.2.13 on 2020-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
