# Generated by Django 2.1.4 on 2020-09-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luci', '0002_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('friendshipness', models.FloatField(default=0.0)),
                ('emotion_resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='luci.Emotion')),
            ],
        ),
    ]
