# Generated by Django 2.2.13 on 2021-01-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luci', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_datetime',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
