# Generated by Django 2.2.13 on 2021-01-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luci', '0005_message_message_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='possible_responses',
            field=models.ManyToManyField(related_name='_message_possible_responses_+', to='luci.Message'),
        ),
    ]
