# Generated by Django 2.2.13 on 2021-05-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luci', '0007_auto_20210131_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reference',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.BinaryField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('reference', 'text')},
        ),
    ]
