# Generated by Django 2.2.13 on 2021-05-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luci', '0008_auto_20210501_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.BinaryField(),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('reference', 'quote')},
        ),
    ]
