# Generated by Django 2.2.13 on 2021-08-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luci', '0011_auto_20210504_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.BinaryField(max_length=1000),
        ),
    ]
