# Generated by Django 2.2.13 on 2022-05-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luci', '0012_auto_20210817_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('pos_tag', models.CharField(blank=True, max_length=10, null=True)),
                ('lemma', models.CharField(blank=True, max_length=100, null=True)),
                ('entity', models.CharField(blank=True, max_length=10, null=True)),
                ('polarity', models.FloatField(null=True)),
                ('length', models.IntegerField()),
            ],
        ),
    ]
